ControlMarcaje/Models/Marcaje.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMarcaje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcaje
    {
        public int id { get; set; }
        public Nullable<int> empleado { get; set; }
        public Nullable<System.DateTime> dia_laboral { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_entrada_almuerzo { get; set; }
        public Nullable<System.TimeSpan> hora_salida_almuerzo { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
    
        public virtual Empleado Empleado1 { get; set; }
    }
}

ControlMarcaje/Controllers/MarcajesController.cs
using ControlMarcaje.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlMarcaje.Controllers
{
    public class MarcajesController : Controller
    {

        ApiMarcajesController apiMarcajes = new ApiMarcajesController();
        ApiEmpleadosController apiEmpleados = new ApiEmpleadosController();
        
        
        public ActionResult Index(int? num_empleado)
        {
            if (num_empleado == null)
            {
                return RedirectToAction("Index", "Empleados");
            }
            IEnumerable<Marcaje> marcajesByEmpleado = apiMarcajes.GetMarcajes().ToList().
                Where(x => x.empleado == num_empleado && x.dia_laboral.Value.ToShortDateString().Equals(DateTime.Now.ToShortDateString()));

            if (marcajesByEmpleado.Count() == 0)
            {
                Marcaje marcaje = new Marcaje();
                marcaje.dia_laboral = DateTime.Now;
                marcaje.empleado = num_empleado;
                apiMarcajes.PostMarcaje(marcaje);

                marcajesByEmpleado = apiMarcajes.GetMarcajes().ToList().
                                Where(x => x.empleado == num_empleado && 
                                x.dia_laboral.Value.ToShortDateString().Equals(DateTime.Now.ToShortDateString()));
            }

            return View(marcajesByEmpleado);
        }

        // GET: Marcajes/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Marcajes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marcajes/Create
        [HttpPost]
        public ActionResult Create(string num_empleado, string accion)
        {
            try
            {
                int empleado = int.Parse(num_empleado);
                Marcaje marcaje = apiMarcajes.GetMarcajes().ToList().
                    Where(x => x.empleado == empleado && 
                    x.dia_laboral.Value.ToShortDateString().Equals(DateTime.Now.ToShortDateString())).FirstOrDefault();
                switch (accion)
                {
                    case "hora_entrada":
                        TimeSpan hora_entrada = DateTime.Now.TimeOfDay;
                        marcaje.hora_entrada = hora_entrada;
                        break;
                    case "hora_entrada_almuerzo":
                        TimeSpan hora_entrada_almuerzo = DateTime.Now.TimeOfDay;
                        marcaje.hora_entrada_almuerzo = hora_entrada_almuerzo;
                        break;
                    case "hora_salida_almuerzo":
                        TimeSpan hora_salida_almuerzo = DateTime.Now.TimeOfDay;
                        marcaje.hora_salida_almuerzo = hora_salida_almuerzo;
                        break;
                    case "hora_salida":
                        TimeSpan hora_salida = DateTime.Now.TimeOfDay;
                        marcaje.hora_salida = hora_salida;
                        break;
                }
                apiMarcajes.PutMarcaje(marcaje.id, marcaje);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Marcajes/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Marcajes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Marcajes/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Marcajes/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlMarcaje/Views/Marcajes/Index.cshtml
@model IEnumerable<ControlMarcaje.Models.Marcaje>


@{
    ViewBag.Title = "Control de marcajes";
}

<br />

<h2 class="text-center text-capitalize">@Html.DisplayFor(model => model.FirstOrDefault().Empleado1.nombre_completo)</h2>

<br />

<div class="row">
    <div class="col-lg-12">
        <input type="hidden" value="@Html.DisplayFor(model => model.FirstOrDefault().empleado)" name="id" />
        <a class="btn btn-info" href="@Url.Action("Details/" + @Html.DisplayFor(model => model.FirstOrDefault().empleado), "Empleados")">
            Ver detalles
        </a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-3">
        <div class="card text-center">
            <img src="http://chittagongit.com//images/entrance-icon-png/entrance-icon-png-24.jpg" class="card-img-top" alt="Entrada">
            <div class="card-body text-center">
                <h5 class="card-title">Entrada</h5>
                @using (Html.BeginForm("Create", "Marcajes"))
                {
                    <input type="hidden" value="@Html.DisplayFor(model => model.FirstOrDefault().empleado.Value)" name="num_empleado" />
                    <input type="hidden" value="hora_entrada" name="accion" />
                    <input type="submit" value="Marcar" class="btn btn-primary" />
                }
                <p class="card-text">@Html.DisplayFor(model => model.FirstOrDefault().hora_entrada)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <img src="http://chittagongit.com//images/lunch-icon-png/lunch-icon-png-29.jpg" class="card-img-top" alt="Entrada" style="width:200px; text-align:center">
            <div class="card-body text-center">
                <h5 class="card-title">Entrada almuerzo</h5>
                @using (Html.BeginForm("Create", "Marcajes"))
                {
                    <input type="hidden" value="@Html.DisplayFor(model => model.FirstOrDefault().empleado.Value)" name="num_empleado" />
                    <input type="hidden" value="hora_entrada_almuerzo" name="accion" />
                    <input type="submit" value="Marcar" class="btn btn-primary" />
                }
                <p class="card-text">@Html.DisplayFor(model => model.FirstOrDefault().hora_entrada_almuerzo)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <img src="http://chittagongit.com//images/lunch-icon-png/lunch-icon-png-29.jpg" class="card-img-top" alt="Entrada" style="width:200px; text-align:center">
            <div class="card-body text-center">
                <h5 class="card-title">Salida almuerzo</h5>
                @using (Html.BeginForm("Create", "Marcajes"))
                {
                    <input type="hidden" value="@Html.DisplayFor(model => model.FirstOrDefault().empleado.Value)" name="num_empleado" />
                    <input type="hidden" value="hora_salida_almuerzo" name="accion" />
                    <input type="submit" value="Marcar" class="btn btn-primary" />
                }
                <p class="card-text">@Html.DisplayFor(model => model.FirstOrDefault().hora_salida_almuerzo)</p>
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="card text-center">
            <img src="http://chittagongit.com//images/icon-exit/icon-exit-24.jpg" class="card-img-top" alt="Entrada">
            <div class="card-body text-center">
                <h5 class="card-title">Salida</h5>
                @using (Html.BeginForm("Create", "Marcajes"))
                {
                    <input type="hidden" value="@Html.DisplayFor(model => model.FirstOrDefault().empleado.Value)" name="num_empleado" />
                    <input type="hidden" value="hora_salida" name="accion" />
                    <input type="submit" value="Marcar" class="btn btn-primary" />
                }
                <p class="card-text">@Html.DisplayFor(model => model.FirstOrDefault().hora_salida)</p>
            </div>
        </div>
    </div>
</div>